# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and deploy the application
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Will run on push to the "main" branch

jobs:
  build:

    runs-on: self-hosted # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16 # We can make it more understandable by adding names to the steps
      uses: actions/setup-node@v3.5.0
      with:
        node-version: '16.x' # Change according to the installed version
        cache: 'npm'
    
    - name: Install dependencies
      run: | 
        npm install
        cd frontend
        npm install

    - name: Creating a Production Build of React App
      run: | 
        npm run build
        cd ..
      
  create-envfile:
 
    runs-on: self-hosted
    needs: build # Run only after the 'build' job is completed
 
    steps:
    - name: Create .env file
      # Creates an '.env' file with environment variables
      run: |
        touch .env
        echo NEXT_PUBLIC_SSARMY_AUTHEN=${{ secrets.NEXT_PUBLIC_SSARMY_AUTHEN}} >> .env
        echo NEXT_PUBLIC_SSARMY_AUTHEN=${{ secrets.NEXT_PUBLIC_SSARMY_TRNSECTION}} >> .env
        echo NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}} >> .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}} >> .env

  deploy:
 
    runs-on: self-hosted
    needs: [build, create-envfile] # Run only after the 'build' and 'create-envfile' job is completed
 
    steps:
    - name: Deploy to production 
      # Starts your node js app in 'PM2'
      run: |
        pm2 stop ecosystem.config.js
        pm2 start ecosystem.config.js
        pm2 save
